"""Сопоставление узлов: английские названия из базы кроссов -> ваше дерево.

Зачем: один каталожный номер принадлежит разным артикулам разных
производителей. Без проверки узла поиск подшипника выдаёт интеркулер.

Ключ — короткий код узла. Он проставляется и артикулам из базы кроссов,
и вашим категориям. Кросс срабатывает, только если узлы совпали.

Правила проверяются по порядку: более специфичные выше.
"""

# английские ключевые слова -> код узла
CROSS_RULES: list[tuple[str, str]] = [
    ("wheel bearing", "hub"),
    ("hub bearing", "hub"),
    ("wheel hub", "hub"),
    ("brake disc", "brake"),
    ("brake pad", "brake"),
    ("brake caliper", "brake"),
    ("brake cylinder", "brake"),
    ("brake hose", "brake"),
    ("brake drum", "brake"),
    ("abs", "brake"),
    ("brake", "brake"),
    ("headlight", "light"),
    ("headlamp", "light"),
    ("fog light", "light"),
    ("tail light", "light"),
    ("indicator", "light"),
    ("bulb", "light"),
    ("lamp", "light"),
    ("light", "light"),
    ("radiator", "cooling"),
    ("intercooler", "cooling"),
    ("water pump", "cooling"),
    ("thermostat", "cooling"),
    ("cooling fan", "cooling"),
    ("coolant", "cooling"),
    ("expansion tank", "cooling"),
    ("shock absorber", "susp"),
    ("suspension", "susp"),
    ("strut", "susp"),
    ("control arm", "susp"),
    ("stabiliser", "susp"),
    ("stabilizer", "susp"),
    ("ball joint", "susp"),
    ("spring", "susp"),
    ("bush", "susp"),
    ("track control", "susp"),
    ("wishbone", "susp"),
    ("tie rod", "steer"),
    ("steering", "steer"),
    ("rack", "steer"),
    ("drive shaft", "drive"),
    ("joint, drive", "drive"),
    ("cv joint", "drive"),
    ("propshaft", "drive"),
    ("differential", "drive"),
    ("clutch", "clutch"),
    ("flywheel", "clutch"),
    ("gearbox", "gearbox"),
    ("transmission", "gearbox"),
    ("gear lever", "gearbox"),
    ("turbo", "engine"),
    ("cylinder head", "engine"),
    ("gasket", "engine"),
    ("camshaft", "engine"),
    ("crankshaft", "engine"),
    ("piston", "engine"),
    ("timing belt", "engine"),
    ("timing chain", "engine"),
    ("oil pump", "engine"),
    ("valve cover", "engine"),
    ("engine mount", "engine"),
    ("oil filter", "engine"),
    ("air filter", "engine"),
    ("spark plug", "engine"),
    ("glow plug", "engine"),
    ("ignition coil", "engine"),
    ("injector", "engine"),
    ("throttle", "engine"),
    ("engine", "engine"),
    ("exhaust", "exhaust"),
    ("catalytic", "exhaust"),
    ("silencer", "exhaust"),
    ("muffler", "exhaust"),
    ("particulate filter", "exhaust"),
    ("fuel pump", "fuel"),
    ("fuel filter", "fuel"),
    ("fuel tank", "fuel"),
    ("fuel", "fuel"),
    ("alternator", "electric"),
    ("starter", "electric"),
    ("sensor", "electric"),
    ("switch", "electric"),
    ("relay", "electric"),
    ("control unit", "electric"),
    ("battery", "electric"),
    ("wiring", "electric"),
    ("ecu", "electric"),
    ("mirror", "glass"),
    ("window", "glass"),
    ("windscreen", "glass"),
    ("windshield", "glass"),
    ("wiper", "glass"),
    ("glass", "glass"),
    ("bumper", "body"),
    ("bonnet", "body"),
    ("hood", "body"),
    ("fender", "body"),
    ("wing", "body"),
    ("door", "body"),
    ("boot lid", "body"),
    ("grille", "body"),
    ("body", "body"),
    ("air conditioning", "climate"),
    ("compressor", "climate"),
    ("heater", "climate"),
    ("evaporator", "climate"),
    ("blower", "climate"),
    ("seat", "interior"),
    ("airbag", "interior"),
    ("dashboard", "interior"),
    ("steering wheel", "interior"),
    ("seat belt", "interior"),
    ("trim", "interior"),
    ("wheel rim", "wheel"),
    ("tyre", "wheel"),
    ("tire", "wheel"),
]

# ваши разделы дерева -> код узла
SECTION_NODES: dict[str, str] = {
    "Кузов": "body",
    "Оптика": "light",
    "Стёкла и зеркала": "glass",
    "Двигатель": "engine",
    "Трансмиссия": "gearbox",
    "Ходовая часть": "susp",
    "Рулевое управление": "steer",
    "Тормозная система": "brake",
    "Выхлопная система": "exhaust",
    "Топливная система": "fuel",
    "Салон": "interior",
    "Электрика": "electric",
    "Климат и отопление": "climate",
    "Мультимедиа": "interior",
    "Колёса": "wheel",
    "Прочее": None,
}

# узлы конкретных категорий, где раздел даёт слишком грубый ответ
CATEGORY_NODES: dict[str, str] = {
    "Ступица": "hub",
    "Подшипник ступицы": "hub",
    "Привод передний левый": "drive",
    "Привод передний правый": "drive",
    "Привод задний": "drive",
    "Карданный вал": "drive",
    "Редуктор задний": "drive",
    "Редуктор передний": "drive",
    "Сцепление": "clutch",
    "Корзина сцепления": "clutch",
    "Маховик": "clutch",
    "Радиатор охлаждения": "cooling",
    "Радиатор кондиционера": "climate",
    "Радиатор печки": "climate",
    "Помпа": "cooling",
    "Интеркулер": "cooling",
    "Вентилятор охлаждения": "cooling",
    "Расширительный бачок": "cooling",
    "Компрессор кондиционера": "climate",
    "Генератор": "electric",
    "Стартер": "electric",
    "Форсунка": "engine",
    "Катушка зажигания": "engine",
}


def node_for_cross(name_en: str | None) -> str | None:
    """Узел артикула по его английскому названию."""
    if not name_en:
        return None
    low = name_en.lower()
    for key, node in CROSS_RULES:
        if key in low:
            return node
    return None
